server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Automatically routes requests to services registered in Eureka
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: classroom-service
          uri: lb://CLASSROOM-SERVICE
          predicates:
            - Path=/api/classrooms/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
