server:
  port: 8761  # Eureka Server runs on port 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false  # The server doesn?t register itself
    fetch-registry: false  # The server doesn?t fetch registry
  server:
    wait-time-in-ms-when-sync-empty: 0
